version: '2.1'
services:
  doorbell:
    build: 
      context: doorbell
      dockerfile: Dockerfile
    privileged: true
    restart: always
    network_mode: host
  # presence:
  #   build: ./presence
  #   cap_add:
  #     - NET_ADMIN
  #   restart: always
  #   network_mode: host
  # nfc:
  #   build: ./nfc
  #   devices:
  #     - "/dev/tty:S0:/dev/tty:S0"
  #   restart: always
  #   network_mode: host